[project]
name = "229catan"
version = "0.1.0"
description = "Catan initial placement model. Final Project for CS229."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
]
